name: Train and test Rasa

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rasa Train and Test GitHub Action
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          data_validate: true # Kiểm tra lỗi của file data và domain
          rasa_train: true # chạy rasa train
          rasa_test: true # chạy rasa test
          test_args: --fail-on-prediction-errors # báo lỗi pipeline khi project xảy ra lỗi
          test_type: all # Run both 'core' and 'nlu' tests
      - name: Upload model
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@master
        with:
          name: model
          path: models
      - name: Store test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            results
            reports